spring:
  application:
    name: trading-service
  profiles:
    active: local
  kafka:
    topics:
      order-trading-topic: order-trading-topic
    consumer:
      group-id: group_id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

server:
  port: 9091
  servlet:
    context-path: /order-processor